# view all routes: app/console debug:router
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

hip_app:
    resource: "@HipAppBundle/Resources/config/routing.yml"
    prefix:   /api/v1/
